name: Build-Test-Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-test-unit:
    runs-on: ubuntu-latest
    steps:
    - name: Repo Chekout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm i
    - name: Run Unit Tests 
      run: npm run test:unit
    - name: Display SoftUni Username
      run: echo "mr.d.dimitrov"

  build-test-ui:
    needs: build-test-unit
    runs-on: ubuntu-latest
    steps:
    - name: Repo Chekout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm i
    - name: Install Playwright
      run: npx playwright install
    - name: Run App
      run: npm run start &
    - name: Run UI Tests
      run: npm run test:ui
      